---
- hosts: all
  remote_user: markbame
  sudo: yes
  roles:
     - markbame
     - hhvm
     - mariadb
     - memcached
     - nginx
     - deployment
     - nodejs
  vars:
    mysql_root_password: red10210
    web_user: www-data
    web_group: www-data
 
     
