---

- name: Install memcached server
  run_once: false
  apt: name=memcached state=present

- name: Do memcached config
  run_once: false
  template: src=etc/memcached.conf dest=/etc/memcached.conf owner=root group=root mode=0644
  notify: memcached restart
